### ISSUE TITLE
Version information here is going to be stale

### ISSUE THREAD

**Issue by jacobq** [mayankchoubey/deno-in-2-hours#2]
(First off, thanks for making this! Having used Node.js extensively I was looking for a quick run-down / cheat-sheet to compliment the API docs)

I noticed in the introduction (of `README.md`) that there's currently a line like this:

> The latest release of Deno is `1.9.0`.

This is already out of date (at the time of writing the latest is `1.11.1`), and even if it's updated it is destined to become out of date frequently as new releases are published. If the goal is to inform the reader of the latest version then perhaps we should replace this with a link to https://github.com/denoland/deno/releases, which will always be up to date. If the reason is to give the reader some context about the current state of the cheat sheet (e.g. imagine that Deno 2.0.0 has been released -- then some things here may have been removed or otherwise changed) maybe it should say something like this instead:

> This guide was written to match version `1.9.0` of Deno.

**Comment by mayankchoubey** [comment]
Hi Jacob,

Thanks for the inputs. You're right! I didn't realize at the time of writing.

I've updated the README.md with your suggestion. 

Also, updated it with some new features that came in recent Deno releases.

Please check it out.

Also, if you're interested in Deno vs Node.js performance comparison, please check it here: https://mayankchoubey.github.io/Deno-vs-Node-Performance/. This is from one of from other repos.

Let me know if you have suggestions on the performance one.
